"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.writeCodeGenerationWarning = void 0;
/**
 * Writes a comment to the output, warning that the file is generated.
 */
function writeCodeGenerationWarning(writer) {
    writer.writeDelimitedCommentParagraph([
        "This code was generated by a Yellicode template.",
        "",
        "Changes to this file may cause incorrect behavior and will be lost if the code is regenerated."
    ]);
}
exports.writeCodeGenerationWarning = writeCodeGenerationWarning;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidXRpbHMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJ1dGlscy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7QUFFQTs7R0FFRztBQUNILFNBQWdCLDBCQUEwQixDQUFDLE1BQW9CO0lBQzNELE1BQU0sQ0FBQyw4QkFBOEIsQ0FBQztRQUNsQyxrREFBa0Q7UUFDbEQsRUFBRTtRQUNGLGdHQUFnRztLQUNuRyxDQUFDLENBQUM7QUFDUCxDQUFDO0FBTkQsZ0VBTUMifQ==