import { TypeScriptWriter } from '@yellicode/typescript';

/**
 * Writes a comment to the output, warning that the file is generated.   
 */
export function writeCodeGenerationWarning(writer: TypeScriptWriter): void {
    writer.writeJsDocLines([
        "This code was generated by a Yellicode template.",
        "",
        "Changes to this file may cause incorrect behavior and will be lost if the code is regenerated."
    ]);
}