/*
* This code was generated by a Yellicode template.
* 
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
*/
using Microsoft.EntityFrameworkCore;

namespace Bookstore.Api.Data
{
	public partial class BookStoreModelConfiguration
	{
		static partial void OnBuildModel(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<BookAuthor>()
				.HasKey(bc => new { bc.BookId, bc.AuthorId});

			modelBuilder.Entity<BookAuthor>()
				.HasOne(bc => bc.Book)
				.WithMany(b => b.Authors)
				.HasForeignKey(bc => bc.BookId);
		}
	}
}
