/*
* This code was generated by a Yellicode template.
* 
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
*/
using Microsoft.EntityFrameworkCore;

namespace Bookstore.Api.Data
{
	public partial class BookstoreContext
	{
		public DbSet<Author> AuthorSet { get; set; }
		public DbSet<Book> BookSet { get; set; }
		public DbSet<Category> CategorySet { get; set; }
		public DbSet<Language> LanguageSet { get; set; }
	}
}
